# Nba Regular Season 2018-19 Data Challenge

Your task will be to take the dataset given, and create an analysis answering the following 10 questions. This project will again test your knowledge of pandas in order to find the answers needed given the data you are presented with.

In [2]:
import numpy as np

In [3]:
import pandas as pd

pd.set_option('display.max_columns', 500)

In [4]:
NBA_df = pd.read_csv('nbastats2018-2019.csv', sep = ',')
NBA_df

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,Rebounds,FT%,FTA,FG3%,FG3A,FG%,FGA,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
0,Alex Abrines,78,200,Oklahoma City Thunder,25,5455236,5.3,0.2,0.5,0.6,1.5,0.923,0.4,0.323,4.1,0.357,5.1,19.0,31,6.3,0.1,0.6,0.6,0.053,12.2,-3.4,-0.2
1,Quincy Acy,79,240,Phoenix Suns,28,213949,1.7,0.4,0.1,0.8,2.5,0.700,1.0,0.133,1.5,0.222,1.8,12.3,10,2.9,-0.1,0.0,-0.1,-0.022,9.2,-5.9,-0.1
2,Jaylen Adams,74,190,Atlanta Hawks,22,236854,3.2,0.1,0.4,1.9,1.8,0.778,0.3,0.338,2.2,0.345,3.2,12.6,34,7.6,-0.1,0.2,0.1,0.011,13.5,-4.4,-0.3
3,Steven Adams,84,265,Oklahoma City Thunder,25,24157304,13.9,1.0,1.5,1.6,9.5,0.500,3.7,0.000,0.0,0.595,10.1,33.4,80,18.5,5.1,4.0,9.1,0.163,16.4,2.7,3.2
4,Bam Adebayo,82,255,Miami Heat,21,2955840,8.9,0.8,0.9,2.2,7.3,0.735,2.8,0.200,0.2,0.576,5.9,23.3,82,17.9,3.4,3.4,6.8,0.171,15.8,3.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,Trae Young,74,180,Atlanta Hawks,20,5356440,19.1,0.2,0.9,8.1,3.7,0.829,5.1,0.324,6.0,0.418,15.5,30.9,81,17.0,2.5,0.7,3.3,0.062,28.4,-1.1,0.6
517,Cody Zeller,84,240,Charlotte Hornets,26,13528090,10.1,0.8,0.8,2.1,6.8,0.787,2.9,0.273,0.4,0.551,7.0,25.4,49,17.2,2.6,1.2,3.9,0.150,16.3,2.0,1.2
518,Tyler Zeller,84,253,Atlanta Hawks,29,106974,7.7,0.5,0.2,0.7,4.0,0.778,3.0,0.000,0.2,0.533,5.0,15.5,6,17.3,0.2,0.1,0.3,0.167,20.1,-2.2,0.0
519,Ante Zizic,83,254,Cleveland Cavaliers,22,1952760,7.8,0.4,0.2,0.9,5.4,0.705,2.2,NaN,0.0,0.553,5.6,18.3,59,16.2,1.7,0.3,2.0,0.087,18.2,-3.1,-0.3
520,Ivica Zubac,85,240,Los Angeles Clippers,21,1544951,8.9,0.9,0.2,1.1,6.1,0.802,2.1,NaN,0.0,0.559,6.4,17.6,59,18.9,1.9,1.3,3.2,0.148,20.3,-0.3,0.5

In [5]:
NBA_df2 = NBA_df['Age'].mean()
print(NBA_df2)

25.900191938579656

# What was the average age of player in the league?

In [6]:
NBA_df2 = NBA_df['Age'].mean()
print(NBA_df2)

25.900191938579656

# What player scored the most points?

In [7]:
NBA_df.sort_values(by = 'Points',ascending=False)
#James Harden

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,Rebounds,FT%,FTA,FG3%,FG3A,FG%,FGA,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
202,James Harden,77,220,Houston Rockets,29,30431854,36.1,0.7,2.0,7.5,6.6,0.879,11.0,0.368,13.2,0.442,24.5,36.8,78,30.6,11.4,3.8,15.2,0.254,40.5,11.7,9.9
179,Paul George,81,220,Oklahoma City Thunder,28,30560700,28.0,0.4,2.2,4.1,8.2,0.839,7.0,0.386,9.8,0.438,21.0,36.9,77,23.3,7.0,4.9,11.9,0.201,29.5,5.5,5.3
15,Giannis Antetokounmpo,83,242,Milwaukee Bucks,24,24157304,27.7,1.5,1.3,5.9,12.5,0.729,9.5,0.256,2.8,0.578,17.3,32.8,72,30.9,8.9,5.5,14.4,0.292,32.3,10.8,7.6
151,Joel Embiid,84,250,Philadelphia 76ers,24,25467250,27.5,1.9,0.7,3.7,13.6,0.804,10.1,0.300,4.1,0.484,18.7,33.7,64,26.1,4.9,3.8,8.7,0.194,33.3,4.1,3.3
253,LeBron James,80,250,Los Angeles Lakers,34,35654150,27.4,0.6,1.3,8.3,8.5,0.665,7.6,0.339,5.9,0.510,19.9,35.2,55,25.6,4.7,2.6,7.2,0.179,31.6,8.1,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,Donte Grantham,80,215,NaN,23,-,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000,0.7,0.000,0.7,0.7,3,-38.1,0.0,0.0,0.0,-0.946,40.7,-38.9,0.0
242,Andre Ingram,75,190,Los Angeles Lakers,33,76236,0.0,0.0,0.3,0.0,0.5,NaN,0.0,0.000,0.8,0.000,1.5,3.8,4,-11.9,-0.1,0.0,-0.1,-0.408,19.3,-19.9,-0.1
498,Okaro White,80,205,Washington Wizards,26,264919,0.0,0.0,0.0,0.0,0.7,NaN,0.0,0.000,0.7,0.000,0.7,2.0,3,-4.5,0.0,0.0,0.0,-0.251,14.1,-19.2,0.0
442,Kobi Simmons,77,166,Cleveland Cavaliers,21,76236,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,NaN,0.0,2.0,1,0.0,0.0,0.0,0.0,-0.033,0.0,-7.3,0.0
14,Ike Anigbogu,82,250,Indiana Pacers,20,1378242,0.0,0.3,0.0,0.3,1.0,NaN,0.0,NaN,0.0,0.000,1.0,2.0,3,-6.0,-0.1,0.0,-0.1,-0.480,29.1,-14.0,0.0

# What player had the most blocks during the season? Was it a post player (F/C)?

In [8]:
NBA_df.describe(include = 'all')
NBA_df.sort_values(by = 'Blocks', ascending = False)
#Myles Turner has the most blocks  If a guard is considered a post player then yes if not then no.

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,Rebounds,FT%,FTA,FG3%,FG3A,FG%,FGA,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
476,Myles Turner,83,250,Indiana Pacers,22,3410284,13.3,2.7,0.8,1.6,7.2,0.736,2.7,0.388,2.6,0.487,10.5,28.6,74,18.0,1.9,4.4,6.3,0.144,20.0,3.3,2.8
123,Anthony Davis,82,253,New Orleans Pelicans,25,25434263,25.9,2.4,1.6,3.9,12.0,0.794,7.7,0.331,2.6,0.517,18.3,33.0,56,30.3,6.4,3.1,9.5,0.247,29.5,8.5,4.9
419,Mitchell Robinson,85,240,New York Knicks,20,1485440,7.3,2.4,0.8,0.6,6.4,0.600,2.0,NaN,0.0,0.694,4.4,20.6,66,22.0,4.0,2.2,6.1,0.217,12.1,5.7,2.7
183,Rudy Gobert,85,245,Utah Jazz,26,23241573,15.9,2.3,0.8,2.0,12.9,0.636,6.4,NaN,0.0,0.669,8.8,31.8,81,24.6,8.7,5.7,14.4,0.268,17.8,7.0,5.9
303,Brook Lopez,84,270,Milwaukee Bucks,30,3382000,12.5,2.2,0.6,1.2,4.9,0.842,1.6,0.365,6.3,0.452,9.7,28.7,81,14.6,2.3,4.3,6.7,0.138,16.7,2.7,2.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,Duncan Robinson,80,210,NaN,24,-,3.3,0.0,0.3,0.3,1.3,0.667,0.4,0.286,2.3,0.391,3.1,10.7,15,7.6,0.0,0.2,0.2,0.051,14.0,-4.2,-0.1
413,Malachi Richardson,78,205,Philadelphia 76ers,23,1569360,1.4,0.0,0.0,0.0,0.6,0.800,0.2,0.320,1.1,0.310,1.3,4.7,22,0.9,-0.2,0.1,-0.1,-0.060,16.4,-10.8,-0.2
410,Davon Reed,77,208,Phoenix Suns,23,1378242,1.2,0.0,0.1,0.3,0.6,NaN,0.0,0.500,0.4,0.417,1.2,4.7,10,8.1,0.0,0.0,0.1,0.064,12.1,-4.2,0.0
259,B.J. Johnson,79,200,Atlanta Hawks,23,94742,3.3,0.0,0.3,0.0,1.1,1.000,0.3,0.429,1.0,0.500,2.6,7.0,7,12.8,0.0,0.0,0.1,0.066,17.4,-8.5,-0.1
147,Trevon Duval,74,189,NaN,20,-,1.7,0.0,0.0,0.7,0.3,NaN,0.0,1.000,0.3,0.667,1.0,2.0,3,38.3,0.1,0.0,0.1,0.537,20.9,9.7,0.0

# Based on the regular season, who had the best chance to win a title given their win percentage?

In [9]:
ws_high = NBA_df.groupby('Team').agg({'WS': ['max',]})
print(ws_high.sort_values(by = ('WS', 'max'), ascending = False))
#Houston Rockets

                          WS
                         max
Team
Houston Rockets         15.2
Utah Jazz               14.4
Milwaukee Bucks         14.4
Portland Trail Blazers  12.1
Oklahoma City Thunder   11.9
Denver Nuggets          11.8
Golden State Warriors   11.5
Minnesota Timberwolves  10.4
Orlando Magic           10.1
Detroit Pistons         10.0
Toronto Raptors          9.5
New Orleans Pelicans     9.5
San Antonio Spurs        9.3
Boston Celtics           9.1
Philadelphia 76ers       8.7
Los Angeles Clippers     8.7
Memphis Grizzlies        8.0
Indiana Pacers           7.6
Brooklyn Nets            7.6
Washington Wizards       7.6
Dallas Mavericks         7.5
Charlotte Hornets        7.4
Los Angeles Lakers       7.2
New York Knicks          7.1
Miami Heat               6.8
Sacramento Kings         6.7
Atlanta Hawks            6.0
Phoenix Suns             5.8
Cleveland Cavaliers      4.9
Chicago Bulls            3.7

# What player had the best 3-pt percentage?

In [10]:
# I'll assume that FG3%	is the same as the NBA's 3P%	3-Point Field Goal Percentage
NBA_df.describe(include = 'all')
NBA_df.head(10).sort_values(by = 'FG3%', ascending = False)
#Jaylen Adams

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,Rebounds,FT%,FTA,FG3%,FG3A,FG%,FGA,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
2,Jaylen Adams,74,190,Atlanta Hawks,22,236854,3.2,0.1,0.4,1.9,1.8,0.778,0.3,0.338,2.2,0.345,3.2,12.6,34,7.6,-0.1,0.2,0.1,0.011,13.5,-4.4,-0.3
0,Alex Abrines,78,200,Oklahoma City Thunder,25,5455236,5.3,0.2,0.5,0.6,1.5,0.923,0.4,0.323,4.1,0.357,5.1,19.0,31,6.3,0.1,0.6,0.6,0.053,12.2,-3.4,-0.2
8,Grayson Allen,77,198,Utah Jazz,23,2074320,5.6,0.2,0.2,0.7,0.6,0.750,1.6,0.323,2.6,0.376,4.7,10.9,38,7.5,-0.4,0.4,0.0,0.002,24.4,-6.8,-0.5
5,Deng Adel,79,200,NaN,21,-,1.7,0.2,0.1,0.3,1.0,1.000,0.2,0.261,1.2,0.306,1.9,10.2,19,2.7,-0.2,0.0,-0.2,-0.054,9.9,-7.3,-0.3
7,Rawle Alkins,77,225,NaN,21,-,3.7,0.0,0.1,1.3,2.6,0.667,1.2,0.250,1.2,0.333,3.9,12.0,10,8.1,-0.1,0.0,-0.1,-0.042,19.0,-6.5,-0.1
6,LaMarcus Aldridge,83,260,San Antonio Spurs,33,22347015,21.3,1.3,0.5,2.4,9.2,0.847,5.1,0.238,0.5,0.519,16.3,33.2,81,22.9,6.4,2.9,9.3,0.167,26.9,1.6,2.5
4,Bam Adebayo,82,255,Miami Heat,21,2955840,8.9,0.8,0.9,2.2,7.3,0.735,2.8,0.200,0.2,0.576,5.9,23.3,82,17.9,3.4,3.4,6.8,0.171,15.8,3.0,2.4
1,Quincy Acy,79,240,Phoenix Suns,28,213949,1.7,0.4,0.1,0.8,2.5,0.700,1.0,0.133,1.5,0.222,1.8,12.3,10,2.9,-0.1,0.0,-0.1,-0.022,9.2,-5.9,-0.1
9,Jarrett Allen,83,237,Brooklyn Nets,20,2034120,10.9,1.5,0.5,1.4,8.4,0.709,3.5,0.133,0.6,0.590,7.1,26.2,80,18.5,4.4,3.3,7.6,0.175,15.9,2.5,2.4
3,Steven Adams,84,265,Oklahoma City Thunder,25,24157304,13.9,1.0,1.5,1.6,9.5,0.500,3.7,0.000,0.0,0.595,10.1,33.4,80,18.5,5.1,4.0,9.1,0.163,16.4,2.7,3.2

# Who played the most minutes during the season

In [11]:
col = 'MP'
most_minutes =  NBA_df.loc[NBA_df[col].idxmax()]
print(most_minutes)
#Bradley Beal played the most minutes during the season

Name              Bradley Beal
Height                      77
Weight                     207
Team        Washington Wizards
Age                         25
Salary                25434263
Points                    25.6
Blocks                     0.7
Steals                     1.5
Assists                    5.5
Rebounds                   5.0
FT%                      0.808
FTA                        5.5
FG3%                     0.351
FG3A                       7.3
FG%                      0.475
FGA                       19.6
MP                        36.9
G                           82
PER                       20.8
OWS                        5.9
DWS                        1.7
WS                         7.6
WS48                      0.12
USG                       28.4
BPM                        2.8
VORP                       3.7
Name: 37, dtype: object

# What player given their player effiecency rating was the clutchest during the season?

In [12]:
NBA_df.describe(include = 'all')
NBA_df.sort_values(by = 'PER', ascending = False)
#Zhou Qi has the highest PER

,Name,Height,Weight,Team,Age,Salary,Points,Blocks,Steals,Assists,Rebounds,FT%,FTA,FG3%,FG3A,FG%,FGA,MP,G,PER,OWS,DWS,WS,WS48,USG,BPM,VORP
405,Zhou Qi,85,210,Houston Rockets,23,506134,2.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,1.000,1.0,1.0,1,80.4,0.0,0.0,0.0,1.261,43.4,9.5,0.0
147,Trevon Duval,74,189,NaN,20,-,1.7,0.0,0.0,0.7,0.3,NaN,0.0,1.000,0.3,0.667,1.0,2.0,3,38.3,0.1,0.0,0.1,0.537,20.9,9.7,0.0
394,Gary Payton II,75,190,Washington Wizards,26,85458,3.7,0.3,1.0,1.3,0.7,NaN,0.0,0.500,0.7,0.625,2.7,5.3,3,36.9,0.1,0.0,0.1,0.358,23.8,14.9,0.1
501,Alan Williams,80,265,NaN,26,-,3.6,0.0,0.2,0.6,3.8,0.500,0.8,0.000,0.2,0.615,2.6,5.2,5,32.9,0.1,0.1,0.2,0.312,25.5,5.8,0.1
15,Giannis Antetokounmpo,83,242,Milwaukee Bucks,24,24157304,27.7,1.5,1.3,5.9,12.5,0.729,9.5,0.256,2.8,0.578,17.3,32.8,72,30.9,8.9,5.5,14.4,0.292,32.3,10.8,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,Okaro White,80,205,Washington Wizards,26,264919,0.0,0.0,0.0,0.0,0.7,NaN,0.0,0.000,0.7,0.000,0.7,2.0,3,-4.5,0.0,0.0,0.0,-0.251,14.1,-19.2,0.0
14,Ike Anigbogu,82,250,Indiana Pacers,20,1378242,0.0,0.3,0.0,0.3,1.0,NaN,0.0,NaN,0.0,0.000,1.0,2.0,3,-6.0,-0.1,0.0,-0.1,-0.480,29.1,-14.0,0.0
242,Andre Ingram,75,190,Los Angeles Lakers,33,76236,0.0,0.0,0.3,0.0,0.5,NaN,0.0,0.000,0.8,0.000,1.5,3.8,4,-11.9,-0.1,0.0,-0.1,-0.408,19.3,-19.9,-0.1
268,Terrence Jones,81,252,Houston Rockets,27,198580,1.0,0.0,0.0,0.0,2.0,0.000,0.5,0.000,1.0,0.250,2.0,2.5,2,-15.8,-0.1,0.0,-0.1,-0.661,47.2,-52.3,-0.1
192,Donte Grantham,80,215,NaN,23,-,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.000,0.7,0.000,0.7,0.7,3,-38.1,0.0,0.0,0.0,-0.946,40.7,-38.9,0.0

# What team had the youngest roster?

In [13]:
grouped_single = NBA_df.reset_index()

grouped_single = NBA_df.groupby('Team').agg({'Age': ['mean',]})
print(grouped_single.sort_values(by = ('Age', 'mean'), ascending = True))
#The youngest team is the Chicago Bulls

                              Age
                             mean
Team
Chicago Bulls           24.312500
Sacramento Kings        24.400000
Orlando Magic           24.533333
New York Knicks         24.625000
Phoenix Suns            24.761905
Portland Trail Blazers  24.857143
Indiana Pacers          25.058824
Denver Nuggets          25.266667
Brooklyn Nets           25.555556
Boston Celtics          25.600000
Memphis Grizzlies       25.647059
Oklahoma City Thunder   25.750000
New Orleans Pelicans    25.777778
Cleveland Cavaliers     26.000000
Charlotte Hornets       26.000000
Detroit Pistons         26.266667
Philadelphia 76ers      26.352941
Atlanta Hawks           26.476190
Los Angeles Lakers      26.625000
Minnesota Timberwolves  26.625000
Washington Wizards      26.764706
Milwaukee Bucks         26.928571
Los Angeles Clippers    27.105263
Utah Jazz               27.133333
Toronto Raptors         27.166667
Golden State Warriors   27.866667
Dallas Mavericks        27.866667
Houston Rockets         27.923077
San Antonio Spurs       28.133333
Miami Heat              28.181818

# Who is the highest paid player during the seasion?

In [14]:
#I tried about 5 different ways but was not able to get it to sort correctly 
NBA_df.describe(include = 'all')
sorted_data = NBA_df.head(10).drop_duplicates(subset=['Salary']).sort_values(by = 'Salary', ascending = False)
print(sorted_data)
# NBA_df.describe(include = 'all')
# #NBA_df.sort_values(by = 'Salary', ascending = False).head(10)
# NBA_df.head(10).drop_duplicates(subset=['Salary']).sort_values(by = 'Salary', ascending = False)

                Name  Height  Weight                   Team  Age    Salary  \
0       Alex Abrines      78     200  Oklahoma City Thunder   25   5455236
4        Bam Adebayo      82     255             Miami Heat   21   2955840
3       Steven Adams      84     265  Oklahoma City Thunder   25  24157304
2       Jaylen Adams      74     190          Atlanta Hawks   22    236854
6  LaMarcus Aldridge      83     260      San Antonio Spurs   33  22347015
1         Quincy Acy      79     240           Phoenix Suns   28    213949
8      Grayson Allen      77     198              Utah Jazz   23   2074320
9      Jarrett Allen      83     237          Brooklyn Nets   20   2034120
5          Deng Adel      79     200                    NaN   21         -

   Points  Blocks  Steals  Assists  Rebounds    FT%  FTA   FG3%  FG3A    FG%  \
0     5.3     0.2     0.5      0.6       1.5  0.923  0.4  0.323   4.1  0.357
4     8.9     0.8     0.9      2.2       7.3  0.735  2.8  0.200   0.2  0.576
3    13.9     1.0     1.5      1.6       9.5  0.500  3.7  0.000   0.0  0.595
2     3.2     0.1     0.4      1.9       1.8  0.778  0.3  0.338   2.2  0.345
6    21.3     1.3     0.5      2.4       9.2  0.847  5.1  0.238   0.5  0.519
1     1.7     0.4     0.1      0.8       2.5  0.700  1.0  0.133   1.5  0.222
8     5.6     0.2     0.2      0.7       0.6  0.750  1.6  0.323   2.6  0.376
9    10.9     1.5     0.5      1.4       8.4  0.709  3.5  0.133   0.6  0.590
5     1.7     0.2     0.1      0.3       1.0  1.000  0.2  0.261   1.2  0.306

    FGA    MP   G   PER  OWS  DWS   WS   WS48   USG  BPM  VORP
0   5.1  19.0  31   6.3  0.1  0.6  0.6  0.053  12.2 -3.4  -0.2
4   5.9  23.3  82  17.9  3.4  3.4  6.8  0.171  15.8  3.0   2.4
3  10.1  33.4  80  18.5  5.1  4.0  9.1  0.163  16.4  2.7   3.2
2   3.2  12.6  34   7.6 -0.1  0.2  0.1  0.011  13.5 -4.4  -0.3
6  16.3  33.2  81  22.9  6.4  2.9  9.3  0.167  26.9  1.6   2.5
1   1.8  12.3  10   2.9 -0.1  0.0 -0.1 -0.022   9.2 -5.9  -0.1
8   4.7  10.9  38   7.5 -0.4  0.4  0.0  0.002  24.4 -6.8  -0.5
9   7.1  26.2  80  18.5  4.4  3.3  7.6  0.175  15.9  2.5   2.4
5   1.9  10.2  19   2.7 -0.2  0.0 -0.2 -0.054   9.9 -7.3  -0.3

# At the end of a game, who WOULDN'T you want on the Free Throw Line?

In [15]:
NBA_df.describe(include = 'all')
FT_bad = NBA_df.groupby('Name').agg({'FT%': ['min',]})
print(FT_bad)
#Aaron Gordon has the lowest FT%

                   FT%
                   min
Name
Aaron Gordon     0.731
Aaron Holiday    0.820
Abdel Nader      0.750
Al Horford       0.821
Al-Farouq Aminu  0.867
...                ...
Zach Collins     0.746
Zach LaVine      0.832
Zaza Pachulia    0.782
Zhaire Smith     0.750
Zhou Qi            NaN

[521 rows x 1 columns]